# Generated by Django 2.0.6 on 2018-06-04 13:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('databaseName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('databaseVersionName', models.CharField(max_length=50)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DatabaseInfo')),
            ],
        ),
        migrations.CreateModel(
            name='InfinaWorkerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workerName', models.CharField(max_length=50)),
                ('workerSurname', models.CharField(max_length=50)),
                ('installationTime', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodInstallationTime', models.DateField(blank=True, default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CustomerInfo')),
                ('databaseversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DatabaseVersion')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductManagerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodManName', models.CharField(max_length=50)),
                ('prodManEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('prodManPhoneNumber', models.IntegerField()),
                ('whenIsProdManResponsible', models.DateField(blank=True, default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CustomerInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProductInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productVersionName', models.CharField(max_length=50)),
                ('productmodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProductModule')),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServerVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverVersionName', models.CharField(max_length=50)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ServerInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalManagerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techManName', models.CharField(max_length=50)),
                ('techManEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('whenIsTechManResponsible', models.DateField(blank=True, default=datetime.datetime.now)),
                ('techManPhoneNumber', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CustomerInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TestProductHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testInstallationTime', models.DateField(blank=True, default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CustomerInfo')),
                ('databaseversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DatabaseVersion')),
                ('productversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProductVersion')),
                ('serverversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ServerVersion')),
            ],
        ),
        migrations.AddField(
            model_name='producthistory',
            name='productversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProductVersion'),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='serverversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ServerVersion'),
        ),
        migrations.AddField(
            model_name='infinaworkerhistory',
            name='producthistory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ProductHistory'),
        ),
        migrations.AddField(
            model_name='infinaworkerhistory',
            name='testproducthistory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TestProductHistory'),
        ),
    ]
